### ISSUE TITLE
Add build CI

### ISSUE THREAD

**Issue by aidanheerdegen** [ACCESS-NRI/cice4#4]
Add build CI to this repo.

Uses the [cice4 package](https://github.com/ACCESS-NRI/spack-packages/tree/main/packages/cice4).

Branch protections should also be added.

**Comment by CodeGat** [comment]
Is the default branch supposed to be `main`? It is currently `initial-upload`. 
What branches should be protected? I know the default branch, but there are `access-esm` branches that I don't know if they are special.

**Comment by aidanheerdegen** [comment]
The package refers to the `access-esm1.5` branch

https://github.com/ACCESS-NRI/spack-packages/blob/main/packages/cice4/package.py#L21

@penguian @harshula is there any reason not to use `main` if this repo was created just for that model?

**Comment by CodeGat** [comment]
Added build-ci for this repo :) 
Still waiting on a resolution for the 'what branches to protect' stuff

**Comment by harshula** [comment]
Hi @CodeGat , The https://github.com/ACCESS-NRI/cice4/tree/access-esm1.5 and https://github.com/ACCESS-NRI/cice4/tree/main branches should be protected.

**Comment by harshula** [comment]
Also, please set the default branch to `main`.

**Comment by CodeGat** [comment]
Done both of those things, see https://github.com/ACCESS-NRI/cice4/settings/branches for protection information

**Comment by harshula** [comment]
> Done both of those things, see https://github.com/ACCESS-NRI/cice4/settings/branches for protection information

Thanks. I don't have access to the settings.
